### ISSUE TITLE
drop the url in this repo

### ISSUE THREAD

**Issue by sethsec-bf** [WithSecureLabs/cloud-wiki#32]
I keep forgetting the url of the wiki, getting to this repo, and then having to go google yet again :)

Would be good in the about section on the top right, or just as a one line link in the readme.

**Comment by chrisphilipov** [comment]
Hi @sethsec-bf thanks a lot for the issue! 

I've added the link to the deployed site in the "About" section in the top right of the main page for now but will close the issue once we finalise the README :)

**Comment by chrisphilipov** [comment]
Added extra info to README in #36 and as such I'm closing the issue now. Thanks for the help :)
